/*--------------------------------------------------|
| dTree 2.05 | www.destroydrop.com/javascript/tree/ |
|---------------------------------------------------|
| Copyright (c) 2002-2003 Geir Landrö               |
|                                                   |
| This script can be used freely as long as all     |
| copyright messages are intact.                    |
|                                                   |
| Updated: 17.04.2003                               |
|--------------------------------------------------*/
function Node(a,b,c,d,e,f,g,h,j){this.id=a;this.pid=b;this.name=c;this.url=d;this.title=e;this.target=f;this.icon=g;this.iconOpen=h;this._io=j||!1;this._hc=this._ls=this._is=!1;this._ai=0;this._p}
function dTree(a){this.config={target:null,folderLinks:!0,useSelection:!0,useCookies:!0,useLines:!0,useIcons:!0,useStatusText:!1,closeSameLevel:!1,inOrder:!1};this.icon={root:"img/base.gif",folder:"img/folder.gif",folderOpen:"img/folderopen.gif",node:"img/page.gif",empty:"img/empty.gif",line:"img/line.gif",join:"img/join.gif",joinBottom:"img/joinbottom.gif",plus:"img/plus.gif",plusBottom:"img/plusbottom.gif",minus:"img/minus.gif",minusBottom:"img/minusbottom.gif",nlPlus:"img/nolines_plus.gif",nlMinus:"img/nolines_minus.gif"};
this.obj=a;this.aNodes=[];this.aIndent=[];this.root=new Node(-1);this.selectedNode=null;this.completed=this.selectedFound=!1}dTree.prototype.add=function(a,b,c,d,e,f,g,h,j){this.aNodes[this.aNodes.length]=new Node(a,b,c,d,e,f,g,h,j)};dTree.prototype.openAll=function(){this.oAll(!0)};dTree.prototype.closeAll=function(){this.oAll(!1)};
dTree.prototype.toString=function(){var a='<div class="dtree">\n';document.getElementById?(this.config.useCookies&&(this.selectedNode=this.getSelected()),a+=this.addNode(this.root)):a+="Browser not supported.";this.selectedFound||(this.selectedNode=null);this.completed=!0;return a+"</div>"};
dTree.prototype.addNode=function(a){var b="",c=0;this.config.inOrder&&(c=a._ai);for(c;c<this.aNodes.length;c++)if(this.aNodes[c].pid==a.id){var d=this.aNodes[c];d._p=a;d._ai=c;this.setCS(d);!d.target&&this.config.target&&(d.target=this.config.target);d._hc&&(!d._io&&this.config.useCookies)&&(d._io=this.isOpen(d.id));!this.config.folderLinks&&d._hc&&(d.url=null);this.config.useSelection&&(d.id==this.selectedNode&&!this.selectedFound)&&(d._is=!0,this.selectedNode=c,this.selectedFound=!0);b+=this.node(d,
c);if(d._ls)break}return b};
dTree.prototype.node=function(a,b){var c='<div class="dTreeNode">'+this.indent(a,b);this.config.useIcons&&(a.icon||(a.icon=this.root.id==a.pid?this.icon.root:a._hc?this.icon.folder:this.icon.node),a.iconOpen||(a.iconOpen=a._hc?this.icon.folderOpen:this.icon.node),this.root.id==a.pid&&(a.icon=this.icon.root,a.iconOpen=this.icon.root),c+='<img id="i'+this.obj+b+'" src="'+(a._io?a.iconOpen:a.icon)+'" alt="" />');if(a.url){c+='<a id="s'+this.obj+b+'" class="'+(this.config.useSelection?a._is?"nodeSel":
"node":"node")+'" href="'+a.url+'"';a.title&&(c+=' title="'+a.title+'"');a.target&&(c+=' target="'+a.target+'"');this.config.useStatusText&&(c+=" onmouseover=\"window.status='"+a.name+"';return true;\" onmouseout=\"window.status='';return true;\" ");if(this.config.useSelection&&(a._hc&&this.config.folderLinks||!a._hc))c+=' onclick="javascript: '+this.obj+".s("+b+');"';c+=">"}else if((!this.config.folderLinks||!a.url)&&a._hc&&a.pid!=this.root.id)c+='<a href="javascript: '+this.obj+".o("+b+');" class="node">';
c+=a.name;if(a.url||(!this.config.folderLinks||!a.url)&&a._hc)c+="</a>";c+="</div>";a._hc&&(c+='<div id="d'+this.obj+b+'" class="clip" style="display:'+(this.root.id==a.pid||a._io?"block":"none")+';">',c+=this.addNode(a),c+="</div>");this.aIndent.pop();return c};
dTree.prototype.indent=function(a,b){var c="";if(this.root.id!=a.pid){for(var d=0;d<this.aIndent.length;d++)c+='<img src="'+(1==this.aIndent[d]&&this.config.useLines?this.icon.line:this.icon.empty)+'" alt="" />';a._ls?this.aIndent.push(0):this.aIndent.push(1);a._hc?(c+='<a href="javascript: '+this.obj+".o("+b+');"><img id="j'+this.obj+b+'" src="',c=this.config.useLines?c+(a._io?a._ls&&this.config.useLines?this.icon.minusBottom:this.icon.minus:a._ls&&this.config.useLines?this.icon.plusBottom:this.icon.plus):
c+(a._io?this.icon.nlMinus:this.icon.nlPlus),c+='" alt="" /></a>'):c+='<img src="'+(this.config.useLines?a._ls?this.icon.joinBottom:this.icon.join:this.icon.empty)+'" alt="" />'}return c};dTree.prototype.setCS=function(a){for(var b,c=0;c<this.aNodes.length;c++)this.aNodes[c].pid==a.id&&(a._hc=!0),this.aNodes[c].pid==a.pid&&(b=this.aNodes[c].id);b==a.id&&(a._ls=!0)};dTree.prototype.getSelected=function(){var a=this.getCookie("cs"+this.obj);return a?a:null};
dTree.prototype.s=function(a){if(this.config.useSelection){var b=this.aNodes[a];if((!b._hc||this.config.folderLinks)&&this.selectedNode!=a){if(this.selectedNode||0==this.selectedNode)eOld=document.getElementById("s"+this.obj+this.selectedNode),eOld.className="node";eNew=document.getElementById("s"+this.obj+a);eNew.className="nodeSel";this.selectedNode=a;this.config.useCookies&&this.setCookie("cs"+this.obj,b.id)}}};
dTree.prototype.o=function(a){var b=this.aNodes[a];this.nodeStatus(!b._io,a,b._ls);b._io=!b._io;this.config.closeSameLevel&&this.closeLevel(b);this.config.useCookies&&this.updateCookie()};dTree.prototype.oAll=function(a){for(var b=0;b<this.aNodes.length;b++)this.aNodes[b]._hc&&this.aNodes[b].pid!=this.root.id&&(this.nodeStatus(a,b,this.aNodes[b]._ls),this.aNodes[b]._io=a);this.config.useCookies&&this.updateCookie()};
dTree.prototype.openTo=function(a,b,c){if(!c)for(c=0;c<this.aNodes.length;c++)if(this.aNodes[c].id==a){a=c;break}a=this.aNodes[a];a.pid!=this.root.id&&a._p&&(a._io=!0,a._is=b,this.completed&&a._hc&&this.nodeStatus(!0,a._ai,a._ls),this.completed&&b?this.s(a._ai):b&&(this._sn=a._ai),this.openTo(a._p._ai,!1,!0))};
dTree.prototype.closeLevel=function(a){for(var b=0;b<this.aNodes.length;b++)this.aNodes[b].pid==a.pid&&(this.aNodes[b].id!=a.id&&this.aNodes[b]._hc)&&(this.nodeStatus(!1,b,this.aNodes[b]._ls),this.aNodes[b]._io=!1,this.closeAllChildren(this.aNodes[b]))};dTree.prototype.closeAllChildren=function(a){for(var b=0;b<this.aNodes.length;b++)this.aNodes[b].pid==a.id&&this.aNodes[b]._hc&&(this.aNodes[b]._io&&this.nodeStatus(!1,b,this.aNodes[b]._ls),this.aNodes[b]._io=!1,this.closeAllChildren(this.aNodes[b]))};
dTree.prototype.nodeStatus=function(a,b,c){eDiv=document.getElementById("d"+this.obj+b);eJoin=document.getElementById("j"+this.obj+b);this.config.useIcons&&(eIcon=document.getElementById("i"+this.obj+b),eIcon.src=a?this.aNodes[b].iconOpen:this.aNodes[b].icon);eJoin.src=this.config.useLines?a?c?this.icon.minusBottom:this.icon.minus:c?this.icon.plusBottom:this.icon.plus:a?this.icon.nlMinus:this.icon.nlPlus;eDiv.style.display=a?"block":"none"};
dTree.prototype.clearCookie=function(){var a=new Date((new Date).getTime()-864E5);this.setCookie("co"+this.obj,"cookieValue",a);this.setCookie("cs"+this.obj,"cookieValue",a)};dTree.prototype.setCookie=function(a,b,c,d,e,f){document.cookie=escape(a)+"="+escape(b)+(c?"; expires="+c.toGMTString():"")+(d?"; path="+d:"")+(e?"; domain="+e:"")+(f?"; secure":"")};
dTree.prototype.getCookie=function(a){var b="",c=document.cookie.indexOf(escape(a)+"=");-1!=c&&(a=c+(escape(a)+"=").length,b=document.cookie.indexOf(";",a),b=-1!=b?unescape(document.cookie.substring(a,b)):unescape(document.cookie.substring(a)));return b};dTree.prototype.updateCookie=function(){for(var a="",b=0;b<this.aNodes.length;b++)this.aNodes[b]._io&&this.aNodes[b].pid!=this.root.id&&(a&&(a+="."),a+=this.aNodes[b].id);this.setCookie("co"+this.obj,a)};
dTree.prototype.isOpen=function(a){for(var b=this.getCookie("co"+this.obj).split("."),c=0;c<b.length;c++)if(b[c]==a)return!0;return!1};Array.prototype.push||(Array.prototype.push=function(){for(var a=0;a<arguments.length;a++)this[this.length]=arguments[a];return this.length});Array.prototype.pop||(Array.prototype.pop=function(){lastElement=this[this.length-1];this.length=Math.max(this.length-1,0);return lastElement});